name: "etl_warehouse"
version: "1.0.0"
config-version: 2 

profile: "warehouse" 

model-paths: ["models"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  etl_warehouse: 
    staging:
      +materialized: view
      +schema: stg
    silver:
      +materialized: table
      +schema: sil

snapshots:
  etl_warehouse:
    +target_schema: snapshots 