sources:
  - name: postgres_crm
    schema: public
    tables:
      - name: project_task
        load_strategy: full
        data_subject: crm
        primary_key: id

      - name: crm_lead
        load_strategy: incremental
        data_subject: customer
        cursor_column: write_date
        initial_value: "2024-01-01"
        primary_key: id

      - name: res_partner
        load_strategy: incremental
        data_subject: customer
        cursor_column: write_date
        initial_value: "2024-01-01"
        primary_key: id

  - name: mariadb_erp
    schema: appdb
    tables:
      - name: tabCustomer
        load_strategy: incremental
        data_subject: customer
        cursor_column: modified
        initial_value: "2024-01-01"
        primary_key: name

  - name: postgres_timesheet
    schema: public
    tables:
      - name: account_account
        load_strategy: incremental
        data_subject: hr
        cursor_column: write_date
        initial_value: "2024-01-01"
        primary_key: id

      - name: attendance_application
        load_strategy: incremental
        data_subject: attendance
        cursor_column: write_date
        initial_value: "2024-01-01"
        primary_key: id

      - name: attendance_summary_log
        load_strategy: incremental
        data_subject: attendance
        cursor_column: write_date
        initial_value: "2024-01-01"
        primary_key: id
